# frozen_string_literal: true

source 'https://rubygems.org'

gem 'puma'
gem 'rerun'
gem 'sinatra'

gem 'rubocop'

gem 'capybara' # Библиотека для системного тестирования веб-приложений
gem 'rspec' # Библиотека для выполнения автоматических тестов для Ruby-приложений
