# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'erb_lint', '~> 0.0.28'

gem 'rubocop', '~> 0.69.0'

gem 'sinatra', '~> 2.0'

gem 'puma', '~> 3.12'

gem 'rerun', '~> 0.13.0'

gem 'wdm', '~> 0.1.1'

gem 'rspec', '~> 3.8'

gem 'capybara', '~> 3.20'
